/**
 * Centralized category definitions and mappings for the Prompt Editor
 */

export const CATEGORY_KEY_MAP: Record<string, string> = {
  subject: "Subject",
  art_style: "Art Style",
  medium: "Medium",
  quality: "Quality",
  characters: "Characters",
  character_traits: "Character Traits",
  facial_features: "Facial Features",
  eyes: "Eyes",
  hair: "Hair",
  body_features: "Body Features",
  breasts: "Breasts",
  genitals: "Genitals",
  anatomy_details: "Anatomy Details",
  hand_details: "Hand Details",
  expression_pose: "Expression/Pose",
  posture: "Posture",
  clothing: "Clothing",
  accessories: "Accessories",
  setting: "Setting",
  environment_details: "Environment Details",
  background_elements: "Background Elements",
  time_of_day: "Time of Day",
  weather: "Weather",
  lighting_effects: "Lighting/Effects",
  themes_moods: "Themes/Moods",
  color_palettes: "Color Palettes",
  camera_angles: "Camera Angles",
  perspectives: "Perspectives",
  camera_settings: "Camera Settings",
  lens_type: "Lens Type",
  composition_rules: "Composition Rules",
  motion_effects: "Motion Effects",
  rendering_engine: "Rendering Engine",
  post_processing: "Post Processing",
  texture_materials: "Texture Materials",
  technology_objects: "Technology/Objects",
  other: "Other",
};

export const LABEL_TO_KEY_MAP: Record<string, string> = Object.entries(
  CATEGORY_KEY_MAP
).reduce(
  (acc, [key, label]) => {
    acc[label] = key;
    return acc;
  },
  {} as Record<string, string>
);

export const CATEGORY_ICONS: Record<string, string> = {
  subject: "i-heroicons-user",
  art_style: "i-heroicons-paint-brush",
  medium: "i-heroicons-photo",
  quality: "i-heroicons-star",
  characters: "i-heroicons-users",
  character_traits: "i-heroicons-identification",
  facial_features: "i-heroicons-face-smile",
  eyes: "i-heroicons-eye",
  hair: "i-heroicons-scissors",
  body_features: "i-heroicons-user-circle",
  breasts: "i-heroicons-heart",
  genitals: "i-heroicons-shield-exclamation",
  anatomy_details: "i-heroicons-finger-print",
  hand_details: "i-heroicons-hand-raised",
  expression_pose: "i-heroicons-face-smile",
  posture: "i-heroicons-arrow-trending-up",
  clothing: "i-heroicons-shopping-bag",
  accessories: "i-heroicons-sparkles",
  setting: "i-heroicons-map-pin",
  environment_details: "i-heroicons-building-office",
  background_elements: "i-heroicons-square-3-stack-3d",
  time_of_day: "i-heroicons-clock",
  weather: "i-heroicons-cloud",
  lighting_effects: "i-heroicons-light-bulb",
  themes_moods: "i-heroicons-face-frown",
  color_palettes: "i-heroicons-swatch",
  camera_angles: "i-heroicons-camera",
  perspectives: "i-heroicons-cube",
  camera_settings: "i-heroicons-cog-6-tooth",
  lens_type: "i-heroicons-magnifying-glass-circle",
  composition_rules: "i-heroicons-squares-2x2",
  motion_effects: "i-heroicons-arrow-path",
  rendering_engine: "i-heroicons-cpu-chip",
  post_processing: "i-heroicons-adjustments-horizontal",
  texture_materials: "i-heroicons-cube-transparent",
  technology_objects: "i-heroicons-rocket-launch",
  other: "i-heroicons-ellipsis-horizontal-circle",
};

export const CATEGORY_ORDER: string[] = [
  "subject",
  "quality",
  "characters",
  "character_traits",
  "facial_features",
  "eyes",
  "hair",
  "body_features",
  "breasts",
  "genitals",
  "anatomy_details",
  "hand_details",
  "expression_pose",
  "posture",
  "clothing",
  "accessories",
  "art_style",
  "medium",
  "camera_angles",
  "perspectives",
  "camera_settings",
  "lens_type",
  "composition_rules",
  "motion_effects",
  "setting",
  "environment_details",
  "background_elements",
  "time_of_day",
  "weather",
  "lighting_effects",
  "themes_moods",
  "color_palettes",
  "rendering_engine",
  "post_processing",
  "texture_materials",
  "technology_objects",
  "other",
];

export const CATEGORY_GROUPS = [
  { key: "basics", items: ["subject", "quality"] },
  {
    key: "character",
    items: [
      "characters",
      "character_traits",
      "facial_features",
      "eyes",
      "hair",
      "body_features",
      "breasts",
      "genitals",
      "anatomy_details",
      "hand_details",
    ],
  },
  { key: "pose", items: ["expression_pose", "posture"] },
  { key: "clothing", items: ["clothing", "accessories"] },
  { key: "style", items: ["art_style", "medium"] },
  {
    key: "camera",
    items: [
      "camera_angles",
      "perspectives",
      "camera_settings",
      "lens_type",
      "composition_rules",
      "motion_effects",
    ],
  },
  {
    key: "environment",
    items: [
      "setting",
      "environment_details",
      "background_elements",
      "time_of_day",
      "weather",
    ],
  },
  {
    key: "atmosphere",
    items: ["lighting_effects", "themes_moods", "color_palettes"],
  },
  {
    key: "technical",
    items: [
      "rendering_engine",
      "post_processing",
      "texture_materials",
      "technology_objects",
    ],
  },
  { key: "other", items: ["other"] },
];
